version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
